//首页
//获取应用实例
const app = getApp()

Page({
    data: {
        navs:[{
          image:"/images/daikuan.png",
          text:"查工资条",
          url:""
        },{
          image:"/images/licai.png",
          text:"发工资",
          url:""
        },{
          image:"/images/suiyicun.png",
          text:"投资理财",
          url:""
        },{
          image:"/images/tahangqia.png",
          text:"投资理财",
          url:""
        },{
          image:"/images/tongzhicundan.png",
          text:"投资理财",
          url:""
        },{
          image:"/images/zhuanzhanghuikuan.png",
          text:"更多",
          url:""
        },{
          image:"/images/zhuanzhanghuikuan.png",
          text:"更多",
          url:""
        },{
          image:"/images/zhuanzhanghuikuan.png",
          text:"更多",
          url:""
        }],
        swiper:"/images/home-bg.png"
      },
})
