//首页
//获取应用实例
const app = getApp()

Page({
    data: {
        navs:[{
          image:"/images/daikuan.png",
          text:"查工资条",
          url:"../wages/wages",
          type:'switchTab'
        },{
          image:"/images/licai.png",
          text:"发工资",
          url:"../building/building",
          type:'navigate'
        },{
          image:"/images/suiyicun.png",
          text:"投资理财",
          url:"../building/building",
          type:'navigate'
        },{
          image:"/images/tahangqia.png",
          text:"投资理财",
          url:"../building/building",
          type:'navigate'
        },{
          image:"/images/tongzhicundan.png",
          text:"投资理财",
          url:"../building/building",
          type:'navigate'
        },{
          image:"/images/zhuanzhanghuikuan.png",
          text:"更多",
          url:"../building/building",
          type:'navigate'
        },{
          image:"/images/zhuanzhanghuikuan.png",
          text:"更多",
          url:"../building/building",
          type:'navigate'
        },{
          image:"/images/zhuanzhanghuikuan.png",
          text:"更多",
          url:"../building/building",
          type:'navigate'
        }],
        swiper:"/images/home-bg.png"
      },
})
